#!/usr/bin/env bash
# Network module — iptables rule generation for --restrict-dns

network_generate_iptables_script() {
    local dns_list="$1"

    if [[ -z "$dns_list" ]]; then
        echo "ERROR: No domains specified" >&2
        return 1
    fi

    cat <<'HEADER'
#!/bin/bash
set -euo pipefail

# Limacode network restriction — iptables rules
# Generated by limacode. Do not edit manually.

# Flush existing OUTPUT rules
iptables -F OUTPUT 2>/dev/null || true

# Allow loopback
iptables -A OUTPUT -o lo -j ACCEPT

# Allow established/related connections
iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Allow Lima private network ranges (required for SSH communication)
iptables -A OUTPUT -d 192.168.0.0/16 -j ACCEPT
iptables -A OUTPUT -d 10.0.0.0/8 -j ACCEPT

# Allow DNS resolution
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT

HEADER

    local IFS=','
    for domain in $dns_list; do
        cat <<DOMAIN
# Allow ${domain}
for ip in \$(dig +short "${domain}" 2>/dev/null | grep -E '^[0-9]'); do
    iptables -A OUTPUT -d "\$ip" -j ACCEPT 2>/dev/null || true
done

DOMAIN
    done

    cat <<'FOOTER'
# Drop everything else
iptables -P OUTPUT DROP

echo "Network restriction active. Allowed domains only."

# Install cron job to re-resolve DNS every 5 minutes
echo "*/5 * * * * root /usr/local/bin/limacode-refresh-dns.sh" > /etc/cron.d/limacode-dns-refresh
chmod 644 /etc/cron.d/limacode-dns-refresh
FOOTER
}
