#!/bin/bash
# Limacode network restriction script
# This file is generated by limacode and injected into the VM.
# Do not edit manually. Use --restrict-dns to configure.
set -euo pipefail

echo "Limacode: applying network restrictions..."

# This script is generated dynamically by lib/network.sh
# See lib/network.sh:network_generate_iptables_script() for the template.
